### PR TITLE
Add properties to contacts for locking editing

### PR DESCRIPTION
**Pull request by SkylerSeamans**

### CODE REVIEW

**Comment by jrahaim** [comment]
@SkylerSeamans is this in production yet?

**Comment by SkylerSeamans** [comment]
As far as I know, it's not yet in Prod. It could have been merged last week, though.

**Comment by jrahaim** [comment]
👍 for merge once it's in production. 

Discussion: Since isEditing will default to False if the property isn't on the back end yet, my preference would be to not merge it until the backend has it implemented. (this would also block the accompanying App PR). 
If this property defaulted to TRUE then I would be ok merging this.

**Comment by jrahaim** [comment]
@SkylerSeamans as discussed, can you default this to True if the property is missing?

**Comment by SkylerSeamans** [comment]
@jrahaim updated. I think we're OK to merge with this change in place.

**Pull request merged**
