### PR TITLE
Resolves a race condition in TSDKObjectsRequest. Resolves WIZ-2185

### PR DESCRIPTION
**Pull request by SkylerSeamans**

### CODE REVIEW

**Comment by larsacus** [comment]
Based on mike ash's explanation, we could easily use barriers here. Just convert the queue to concurrent and make all writes async. That should literally be the only change from this changeset.

**Comment by SkylerSeamans** [comment]
@larsacus I'll give it a shot.

**Comment by SkylerSeamans** [comment]
@larsacus Struck out on that approach. Sanitizer reports issues when following the concurrent+barrier approach.

**Comment by SkylerSeamans** [comment]
@larsacus hold up on review. I'm seeing sanitizer issues that I didn't see before. Investigating...

**Comment by SkylerSeamans** [comment]
@larsacus changed to the dispatch_once approach. Looks good now.

**Pull request merged**
