### PR TITLE
return TSDKMemberEmail addresses when sending an invite

### PR DESCRIPTION
**Pull request by SkylerSeamans**
Waiting for the backend crew to determine their specs for this. Not yet ready for review.

### CODE REVIEW

**Comment by jrahaim** [comment]
@SkylerSeamans Is this still a thing?

**Comment by SkylerSeamans** [comment]
Yeah, I believe so.

**Comment by SkylerSeamans** [comment]
I'd have to check if this SDK PR is ready to be merged. App PR is still to be done.

**Comment by SkylerSeamans** [comment]
This endpoint is deprecated in CCCp1. Closing.

**Pull request closed without merging**
